#!/bin/bash

# run crontab -e
# then add the following line:
# * * * * * /vagrant/set_fs_ip

N=1
IP="10.24.7.14"
grep "$IP" /var/sipxdata/cfdata/"$N"/vars.xml || sudo -E sed -i.orig '/<X-PRE-PROCESS.*default_password/i\
  <X-PRE-PROCESS cmd="set" data="local_ip_v4='"$IP"'"/>
' /var/sipxdata/cfdata/"$N"/vars.xml

N=2
IP="10.24.7.15"
grep "$IP" /var/sipxdata/cfdata/"$N"/vars.xml || sudo -E sed -i.orig '/<X-PRE-PROCESS.*default_password/i\
  <X-PRE-PROCESS cmd="set" data="local_ip_v4='"$IP"'"/>
' /var/sipxdata/cfdata/"$N"/vars.xml
